genesis.pdf : genesis.tex references.bib
	pdflatex -synctex=1 -interaction=nonstopmode genesis.tex
	pdflatex -synctex=1 -interaction=nonstopmode genesis.tex
	pdflatex -synctex=1 -interaction=nonstopmode genesis.tex

clean : 
	rm genesis.pdf
